services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./WebApi/Images:/usr/share/nginx/html

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  marketplace.webapi:
    image: ${DOCKER_REGISTRY-}marketplacewebapi
    build:
      context: .
      dockerfile: Marketplace.WebAPI/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - connectionstrings__DefaultConnection=Server=sqlserver,1433;Database=master;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./Marketplace.WebAPI/Images:/images
